// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Iface3PartyEC2Metadata is an autogenerated mock type for the Iface3PartyEC2Metadata type
type Iface3PartyEC2Metadata struct {
	mock.Mock
}

// GetMetadata provides a mock function with given fields: p
func (_m *Iface3PartyEC2Metadata) GetMetadata(p string) (string, error) {
	ret := _m.Called(p)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
