// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IfaceEc2 is an autogenerated mock type for the IfaceEc2 type
type IfaceEc2 struct {
	mock.Mock
}

// GetTagValue provides a mock function with given fields: instanceID, name
func (_m *IfaceEc2) GetTagValue(instanceID string, name string) (string, error) {
	ret := _m.Called(instanceID, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(instanceID, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(instanceID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
