// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IfaceAlb is an autogenerated mock type for the IfaceAlb type
type IfaceAlb struct {
	mock.Mock
}

// Deregister provides a mock function with given fields: instanceID, targetGroupArn
func (_m *IfaceAlb) Deregister(instanceID *string, targetGroupArn *string) error {
	ret := _m.Called(instanceID, targetGroupArn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*string, *string) error); ok {
		r0 = rf(instanceID, targetGroupArn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: instanceID, targetGroupArn
func (_m *IfaceAlb) Register(instanceID *string, targetGroupArn *string) error {
	ret := _m.Called(instanceID, targetGroupArn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*string, *string) error); ok {
		r0 = rf(instanceID, targetGroupArn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
